"""cria tabelas iniciais

Revision ID: 3dd525288426
Revises: 
Create Date: 2026-09-18 23:30:23.701901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd525288426'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('sigla', sa.String(length=2), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('regiao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('qtd_empresas', sa.Integer(), nullable=False),
    sa.Column('pessoal_assalariado', sa.Integer(), nullable=False),
    sa.Column('salarios_mil_reais', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_id', 'ano')
    )
    op.create_table('perfil_demografico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('indice_envelhecimento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('idade_mediana', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('razao_sexo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_id', 'ano')
    )
    op.create_table('populacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('populacao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_id', 'ano')
    )
    op.create_table('renda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('rendimento_medio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rendimento_mediano', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_id', 'ano')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('renda')
    op.drop_table('populacao')
    op.drop_table('perfil_demografico')
    op.drop_table('empresas')
    op.drop_table('municipios')
    op.drop_table('estados')
    # ### end Alembic commands ###
