"""cria tabela beneficiarios

Revision ID: 9876135566d9
Revises: 3dd525288426
Create Date: 2026-09-24 16:23:17.718799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9876135566d9'
down_revision: Union[str, None] = '3dd525288426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('qtd_beneficiarios_medicos', sa.Integer(), nullable=False),
    sa.Column('qtd_beneficiarios_odonto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_id', 'ano')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beneficiarios')
    # ### end Alembic commands ###
